---
title: "COVID-19 State Grades Dashboard"
subtitle: "Developed during Broadstreet's COVID-19 Data Project internship."
summary: I designed an interactive dashboard to visualize how well U.S. states report their COVID-19 data.  
date: "2021-02-09"
tags: [design]
image:
  caption: "[Image designed by Tracy Flood](https://learn.broadstreet.io/about-us/)"
  focal_point: center
draft: false
output: html_document
---

The [COVID-19 Data Project](https://covid19dataproject.org/) is a remote internship program that has leveraged the expertise and contributions of more than 600 public health and data-oriented students, researchers, and practitioners since March 2020. With leadership from the [Broadstreet](https://learn.broadstreet.io/) team, the project's volunteers are committed to procuring and exploring the most reliable COVID-19 data for the United States through crowdsourced data collection, outreach, and policy research.

As part of my internship with Broadstreet, I collaborated with other volunteers to design a custom dashboard that visualizes and compares COVID-19 data reporting across U.S. states to better understand how well state departments of health report their data during the pandemic. After establishing a fully interactive prototype using Adobe XD, I wrangled and cleaned crowdsourced data collected by dozens of volunteers, established variable logic based on the detailed grading schema developed by our internship team, and worked with D3.js developers to productionize the dashboard. 

Building this dashboard provided a terrific opportunity to synthesize my narrative, measurement, analytic, and design skills, an experience that exemplifies my multidisciplinary approach to solving problems through data-driven creativity.

[Explore the dashboard](https://www.broadstreet.io/state-grades/).